name: Build on Linux arm64

on:
  push:
    branches: [main]
    paths:
      - ".github/workflows/build-linux-arm64.yml"
      - "CMakeLists.txt"
      - "CefConfig.cmake"
      - "include/**"
      - "src/**"

  pull_request:
    branches: [main]
    paths:
      - "CMakeLists.txt"
      - "CefConfig.cmake"
      - "include/**"
      - "src/**"

env:
  # Customize the CMake build type here (Release, Debug, RelWithDebInfo, etc.)
  BUILD_TYPE: Release

jobs:
  build:
    # The CMake configure and build commands are platform agnostic and should work equally
    # well on Windows or Mac.  You can convert this to a matrix build if you need
    # cross-platform coverage.
    # See: https://docs.github.com/en/free-pro-team@latest/actions/learn-github-actions/managing-complex-workflows#using-a-build-matrix
    runs-on: ubuntu-22.04-arm

    steps:
      - name: Checkout Source
        uses: actions/checkout@v2
        with:
          submodules: "true"

      - name: Cache CEF folders
        uses: actions/cache@v3
        with:
          path: ${{github.workspace}}/dep
          key: ${{ runner.os }}-dep-cef

      - name: Install x11
        run: |
          sudo apt-get install -y libc++-dev libc++abi-dev libx11-dev

      - name: Configure CMake
        run: |
          cmake \
          -B ${{github.workspace}}/build \
          -DCMAKE_C_COMPILER=clang \
          -DCMAKE_CXX_COMPILER=clang++ \
          -DCMAKE_CXX_FLAGS="-stdlib=libc++ -mno-outline-atomics" \
          -DPROJECT_ARCH=arm64 \
          -DTARGET_ARCH=arm64 \
          -DCMAKE_BUILD_TYPE=${{env.BUILD_TYPE}} \
          -DUSE_SANDBOX=ON \
          -DCEFVIEW_WING_NAME=UCefViewHelper \
          -DCEF_SDK_VERSION="126.2.18+g3647d39+chromium-126.0.6478.183" \
          -DCMAKE_INSTALL_PREFIX:PATH=${{github.workspace}}/install

      - name: Build
        # Build your program with the given configuration
        run: cmake --build ${{github.workspace}}/build --config ${{env.BUILD_TYPE}}

      - name: Install
        # Collect the output
        run: cmake --install ${{github.workspace}}/build --config ${{env.BUILD_TYPE}}

      - name: Create artifact
        uses: actions/upload-artifact@v4
        # Upload artifact
        with:
          name: CefViewCore.Linux.Arm64
          path: ${{github.workspace}}/install
